apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: cpu-container
          image: gitlab-registry.nrp-nautilus.io/yg5d6/testcpu
          command: ["/bin/bash", "-c"]
          args: ["cd home; git clone https://github.com/g1y5x3/Confounding_Mitigation_EC.git; cd Confounding_Mitigation_EC; mv ../subjects_40_v6.mat data/; python3 sEMG-Vowels_GA-SVM-RBF.py -s 0 -nsub 1 -group Vowels"]
          resources:
            limits:
              memory: "16G"
              cpu: "16"
            requests:
              memory: "16G"
              cpu: "16"
      restartPolicy: Never
